[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
testpaths = apps tests
python_files = test_*.py
addopts = --strict-markers --strict-config -ra
filterwarnings =
    error
    ignore::DeprecationWarning:celery.*
    ignore::DeprecationWarning:kombu.*
