# Generated by Django 5.2.17 on 2026-10-01 03:48

import apps.tenancy.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=63, unique=True, validators=[apps.tenancy.validators.validate_business_slug])),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('read_only', 'Read-only'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=16)),
                ('country', models.CharField(default='KE', max_length=2)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')), name='business_slug_format')],
            },
        ),
        migrations.CreateModel(
            name='BusinessDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=253, unique=True, validators=[apps.tenancy.validators.validate_host])),
                ('is_primary', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='tenancy.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('business',), name='one_primary_domain_per_business'), models.CheckConstraint(condition=models.Q(('host', django.db.models.functions.text.Lower('host'))), name='domain_host_lowercase')],
            },
        ),
    ]
