# Generated by Django 5.2.17 on 2026-10-01 04:10

import apps.tenancy.colors
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

from apps.core.db import EnableTenantRLS


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=60)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#0F6B5C', max_length=7, validators=[apps.tenancy.colors.validate_primary_color])),
                ('accent_color', models.CharField(default='#F2A900', max_length=7, validators=[apps.tenancy.colors.validate_hex_color])),
                ('support_phone', models.CharField(blank=True, max_length=16)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=16)),
                ('terms_url', models.URLField(blank=True)),
                ('privacy_url', models.URLField(blank=True)),
                ('sms_sender_id', models.CharField(blank=True, max_length=11)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business',), name='one_branding_per_business')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('value', models.JSONField()),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'key'), name='one_value_per_setting')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        EnableTenantRLS("businessbranding"),
        EnableTenantRLS("businesssetting"),
    ]
