# Generated by Django 5.2.17 on 2026-10-01 15:29

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

from apps.core.db import EnableTenantRLS


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tenancy', '0002_branding_and_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('minimum', models.CharField(max_length=20)),
                ('latest', models.CharField(max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('app', 'platform'), name='one_version_per_app')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('body_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_content_type', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'expires_at'], name='idempotency_expiry')],
                'constraints': [models.UniqueConstraint(fields=('business', 'scope', 'key'), name='idempotency_key_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        EnableTenantRLS("idempotencykey"),
    ]
