/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/app/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * X-01 / X-02 Minimum and latest version of an app
         * @description With no row for the app, every version is allowed (minimum "0.0.0").
         */
        get: operations["app_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** X-14 What this invitation is */
        get: operations["auth_invitation_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/{token}/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** X-14 Send code */
        post: operations["auth_invitation_send_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/{token}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** X-12 in the invitation flow: check the code */
        post: operations["auth_invitation_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** X-13 in the invitation flow: set a password; creates the account and signs in */
        post: operations["auth_invitation_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** X-10 Log in */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out this device */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** X-13 Set a new password after a reset; signs in */
        post: operations["auth_password_reset_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** X-11 Send a reset code */
        post: operations["auth_password_reset_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** X-12 Check the reset code */
        post: operations["auth_password_reset_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change my password; signs out my other sessions */
        post: operations["auth_password_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pin-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * X-15 Switch user with a PIN on a registered device
         * @description X-15: identified by the das_device cookie; a PIN signs a person in on it.
         */
        post: operations["auth_pin_switch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh cookie and get a new access token */
        post: operations["auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/business/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** X-01 Branding, basics and maintenance for this business */
        get: operations["business_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A-30 Categories, in price-list order */
        get: operations["console_catalog_categories_list"];
        put?: never;
        /** A-30 Add a category */
        post: operations["console_catalog_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/categories/{id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-30 Rename a category, or switch it on or off */
        post: operations["console_catalog_categories_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/modifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A-30 Modifiers (Express and chargeable preferences) */
        get: operations["console_catalog_modifiers_list"];
        put?: never;
        /** A-30 Add a modifier: a percentage per line or an amount once per order */
        post: operations["console_catalog_modifiers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/modifiers/{id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-30 Change a modifier (applies to new quotes only) */
        post: operations["console_catalog_modifiers_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A-30 Services with their current business-wide price */
        get: operations["console_catalog_services_list"];
        put?: never;
        /** A-30 Add a service (switched off until priced) */
        post: operations["console_catalog_services_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/services/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-30 Switch a service on (needs a current price) */
        post: operations["console_catalog_services_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/services/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-30 Switch a service off (never deleted) */
        post: operations["console_catalog_services_deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/services/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A-30 Price versions, newest first (business-wide, or one branch's overrides) */
        get: operations["console_catalog_prices_list"];
        put?: never;
        /** A-30 Set a price from now or a later time (a new version) */
        post: operations["console_catalog_prices_set"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/services/{id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-30 Rename or move a service; how it's priced only until it has a price */
        post: operations["console_catalog_services_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/catalog/services/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-30 Order the services (the staff app's quick-add buttons) */
        post: operations["console_catalog_services_reorder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A-42 Registered devices */
        get: operations["console_devices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/devices/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-42 Remove a device (ends every session on it) */
        post: operations["console_devices_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["console_invitations_list"];
        put?: never;
        /** A-41 Invite a person */
        post: operations["console_invitations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/invitations/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-41 Cancel an invitation */
        post: operations["console_invitations_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/invitations/{id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-41 Resend an invitation (new link, 7 more days) */
        post: operations["console_invitations_resend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A-42 Signed-in sessions */
        get: operations["console_sessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/sessions/{id}/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A-42 Sign a session out */
        post: operations["console_sessions_sign_out"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * X-15 This device, its branch, lock state and who can switch in
         * @description Identified by the das_device cookie, not by a signed-in person.
         */
        get: operations["devices_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Checks the database and Redis. Returns 503 if either is failing. Answers on any host (it's exempt from business resolution).
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in person */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** S-01 Branches I work at */
        get: operations["me_branches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose my 4-digit PIN for counter devices (first time) */
        post: operations["me_pin_set"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** S-02 Register this device (signs you out of it) */
        post: operations["staff_devices_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a short-lived URL to upload a photo to private storage */
        post: operations["uploads_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the photo arrived */
        post: operations["uploads_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Access: {
            /** @description Access token (15 minutes). Keep it in memory only. */
            access: string;
        };
        AppVersion: {
            app: string;
            platform: string;
            minimum: string;
            latest: string;
        };
        Branch: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        BusinessConfig: {
            business: components["schemas"]["ConfigBusiness"];
            branding: components["schemas"]["ConfigBranding"];
            maintenance: components["schemas"]["Maintenance"];
        };
        Category: {
            /** Format: uuid */
            readonly id: string;
            name_en: string;
            /** @default  */
            name_sw: string;
            readonly position: number;
            readonly is_active: boolean;
        };
        CategoryRequest: {
            name_en: string;
            /** @default  */
            name_sw: string;
        };
        CategoryUpdateRequest: {
            name_en?: string;
            name_sw?: string;
            is_active?: boolean;
        };
        CodeRequest: {
            code: string;
        };
        ConfigBranding: {
            app_name: string;
            logo_url: string;
            primary_color: string;
            accent_color: string;
            support_phone: string;
            whatsapp_phone: string;
            terms_url: string;
            privacy_url: string;
        };
        ConfigBusiness: {
            name: string;
            slug: string;
            country: string;
            currency: string;
            timezone: string;
            language: string;
        };
        /** @description A-42: registered counter devices (name, branch, registered by, last used). */
        ConsoleDevice: {
            /** Format: uuid */
            id: string;
            name: string;
            branch: components["schemas"]["Branch"];
            status: string;
            registered_by: components["schemas"]["SessionPerson"];
            /** Format: date-time */
            last_seen_at: string | null;
        };
        CurrentDevice: {
            device: components["schemas"]["Device"];
            locked: boolean;
            roster: components["schemas"]["RosterEntry"][];
        };
        Device: {
            /** Format: uuid */
            id: string;
            name: string;
            branch: components["schemas"]["Branch"];
            status: string;
        };
        DeviceRegisterRequest: {
            /** @description For example "Front counter tablet". */
            name: string;
            /** Format: uuid */
            branch_id: string;
        };
        Health: {
            status: components["schemas"]["StatusEnum"];
            checks: {
                [key: string]: string;
            };
        };
        HealthDegraded: {
            status: string;
            checks: {
                [key: string]: string;
            };
        };
        Invitation: {
            /** Format: uuid */
            readonly id: string;
            readonly phone: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly role: string;
            readonly rights: components["schemas"]["Rights"];
            readonly branch_ids: string[];
            /** Format: date-time */
            readonly expires_at: string;
            readonly sent_count: number;
            readonly is_open: boolean;
        };
        InvitationAcceptRequest: {
            setup_token: string;
            password: string;
        };
        InvitationCreateRequest: {
            phone: string;
            first_name: string;
            last_name: string;
            role: components["schemas"]["InvitationCreateRoleEnum"];
            branch_ids?: string[];
            rights?: components["schemas"]["RightsInputRequest"];
        };
        /**
         * @description * `manager` - Manager
         *     * `accountant` - Accountant
         *     * `staff` - Staff
         * @enum {string}
         */
        InvitationCreateRoleEnum: "manager" | "accountant" | "staff";
        /**
         * @description * `express` - Express
         *     * `preference` - Preference
         * @enum {string}
         */
        KindEnum: "express" | "preference";
        /**
         * @description * `en` - English
         *     * `sw` - Kiswahili
         * @enum {string}
         */
        LanguageEnum: "en" | "sw";
        LoginRequest: {
            phone: string;
            password: string;
        };
        LoginResponse: {
            /** @description Access token (15 minutes). Keep it in memory only. */
            access: string;
            user: components["schemas"]["Me"];
        };
        Maintenance: {
            active: boolean;
            expected_return: string;
        };
        /** @description The signed-in person. Read-only; a plain serializer so no queries run to build it. */
        Me: {
            /** Format: uuid */
            readonly id: string;
            readonly phone: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly role: components["schemas"]["MeRoleEnum"];
            readonly language: components["schemas"]["LanguageEnum"];
            readonly is_phone_verified: boolean;
            readonly rights: components["schemas"]["Rights"];
            readonly has_pin: boolean;
        };
        /**
         * @description * `owner` - Owner
         *     * `manager` - Manager
         *     * `accountant` - Accountant
         *     * `staff` - Staff
         *     * `rider` - Rider
         *     * `customer` - Customer
         *     * `platform_super_admin` - Platform super admin
         *     * `platform_support` - Platform support
         *     * `platform_finance` - Platform finance
         * @enum {string}
         */
        MeRoleEnum: "owner" | "manager" | "accountant" | "staff" | "rider" | "customer" | "platform_super_admin" | "platform_support" | "platform_finance";
        Message: {
            message: string;
        };
        Modifier: {
            /** Format: uuid */
            readonly id: string;
            readonly name_en: string;
            readonly name_sw: string;
            readonly kind: components["schemas"]["KindEnum"];
            /** Format: decimal */
            readonly percent: string | null;
            /** Format: decimal */
            readonly amount: string | null;
            readonly currency: string;
            readonly applies_to_all: boolean;
            readonly service_ids: string[];
            readonly position: number;
            readonly is_active: boolean;
        };
        ModifierCreateRequest: {
            name_en: string;
            /** @default  */
            name_sw: string;
            kind: components["schemas"]["KindEnum"];
            /** Format: decimal */
            percent?: string | null;
            /** Format: decimal */
            amount?: string | null;
            /** @default true */
            applies_to_all: boolean;
            service_ids?: string[] | null;
        };
        ModifierUpdateRequest: {
            name_en?: string;
            name_sw?: string;
            /** Format: decimal */
            percent?: string | null;
            /** Format: decimal */
            amount?: string | null;
            applies_to_all?: boolean;
            service_ids?: string[];
            is_active?: boolean;
        };
        PaginatedInvitationList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Invitation"][];
        };
        PaginatedPriceList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Price"][];
        };
        PaginatedSessionList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Session"][];
        };
        PasswordChangeRequest: {
            current_password: string;
            new_password: string;
        };
        PhoneRequest: {
            phone: string;
        };
        PinRequest: {
            pin: string;
        };
        PinSwitchRequest: {
            /** Format: uuid */
            user_id: string;
            pin: string;
        };
        Price: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly branch_id: string | null;
            /** Format: decimal */
            readonly unit_price: string;
            /** Format: decimal */
            readonly minimum_charge: string;
            readonly currency: string;
            /** Format: date-time */
            readonly effective_from: string;
            /** Format: date-time */
            readonly effective_to: string | null;
        };
        PriceCreateRequest: {
            /** Format: decimal */
            unit_price: string;
            /**
             * Format: decimal
             * @default 0.00
             */
            minimum_charge: string;
            /** Format: date-time */
            effective_from?: string | null;
            /** Format: uuid */
            branch_id?: string | null;
        };
        /**
         * @description * `per_kg` - Per kg
         *     * `per_item` - Per item
         *     * `flat` - Flat
         * @enum {string}
         */
        PricingModelEnum: "per_kg" | "per_item" | "flat";
        /** @description What X-14 shows: "{Business} invited you to join as {role}" and the phone. */
        PublicInvitation: {
            business_name: string;
            role: string;
            role_label: string;
            first_name: string;
            phone: string;
        };
        ReorderRequest: {
            service_ids: string[];
        };
        ResetConfirmRequest: {
            reset_token: string;
            password: string;
        };
        ResetToken: {
            /** @description Single use, valid for 10 minutes. */
            reset_token: string;
        };
        Rights: {
            accept_cash: boolean;
            give_discounts: boolean;
            correct_prices: boolean;
        };
        RightsInputRequest: {
            /** @default false */
            accept_cash: boolean;
            /** @default false */
            give_discounts: boolean;
            /** @default false */
            correct_prices: boolean;
        };
        /** @description X-15 shows first name and surname initial ("Wanjiru K."); never phone numbers. */
        RosterEntry: {
            /** Format: uuid */
            id: string;
            first_name: string;
            readonly last_initial: string;
            role: string;
        };
        Service: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly category_id: string;
            readonly code: string;
            readonly name_en: string;
            readonly name_sw: string;
            readonly pricing_model: components["schemas"]["PricingModelEnum"];
            readonly unit: components["schemas"]["UnitEnum"];
            readonly position: number;
            readonly is_active: boolean;
            readonly current_price: components["schemas"]["Price"] | null;
        };
        ServiceCreateRequest: {
            /** Format: uuid */
            category_id: string;
            code: string;
            name_en: string;
            /** @default  */
            name_sw: string;
            pricing_model: components["schemas"]["PricingModelEnum"];
            unit: components["schemas"]["UnitEnum"];
        };
        ServiceUpdateRequest: {
            /** Format: uuid */
            category_id?: string;
            name_en?: string;
            name_sw?: string;
            pricing_model?: components["schemas"]["PricingModelEnum"];
            unit?: components["schemas"]["UnitEnum"];
        };
        /** @description A-42: every signed-in session per person (device, browser, last active). */
        Session: {
            /** Format: uuid */
            id: string;
            user: components["schemas"]["SessionPerson"];
            kind: string;
            device: components["schemas"]["SessionDevice"] | null;
            user_agent: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at: string;
            readonly is_current: boolean;
        };
        SessionDevice: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        SessionPerson: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            role: string;
        };
        SetupToken: {
            /** @description Single use, valid for 10 minutes. */
            setup_token: string;
        };
        StartUploadRequest: {
            content_type: string;
            /** @description Bytes. */
            size: number;
        };
        /**
         * @description * `ok` - ok
         *     * `degraded` - degraded
         * @enum {string}
         */
        StatusEnum: "ok" | "degraded";
        /**
         * @description * `kg` - kg
         *     * `item` - item
         *     * `pair` - pair
         *     * `set` - set
         * @enum {string}
         */
        UnitEnum: "kg" | "item" | "pair" | "set";
        Upload: {
            /** Format: uuid */
            id: string;
            content_type: string;
            size: number;
            status: string;
        };
        UploadTicket: {
            /** Format: uuid */
            upload_id: string;
            /** @description PUT the file here within 5 minutes. */
            url: string;
            method: string;
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        VerifyCodeRequest: {
            phone: string;
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    app_version: {
        parameters: {
            query?: {
                app?: string;
                platform?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppVersion"];
                };
            };
        };
    };
    auth_invitation_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicInvitation"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_invitation_send_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_invitation_verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupToken"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_invitation_accept: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetToken"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_change: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_pin_switch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinSwitchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Access"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    business_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessConfig"];
                };
            };
        };
    };
    console_catalog_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    console_catalog_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_modifiers_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Modifier"][];
                };
            };
        };
    };
    console_catalog_modifiers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifierCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Modifier"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_modifiers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ModifierUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Modifier"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_services_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"][];
                };
            };
        };
    };
    console_catalog_services_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_services_activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_services_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_prices_list: {
        parameters: {
            query?: {
                branch_id?: string;
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPriceList"];
                };
            };
        };
    };
    console_catalog_prices_set: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Price"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_services_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ServiceUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_catalog_services_reorder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"][];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_devices_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleDevice"][];
                };
            };
        };
    };
    console_devices_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_invitations_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInvitationList"];
                };
            };
        };
    };
    console_invitations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_invitations_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_invitations_resend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    console_sessions_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSessionList"];
                };
            };
        };
    };
    console_sessions_sign_out: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    devices_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentDevice"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDegraded"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_branches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
        };
    };
    me_pin_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    staff_devices_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope with retry_after */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploads_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartUploadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploads_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
