# Generated by Django 5.2.17 on 2026-10-03 18:36

import apps.catalog.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.manager
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models

from apps.core.db import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('tenancy', '0002_branding_and_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # For the constraint that keeps price versions from overlapping. A trusted
        # extension: the database owner (dial_owner) may create it.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='PriceModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_sw', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('express', 'Express'), ('preference', 'Preference')], max_length=12)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('applies_to_all', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
            ],
            options={
                'ordering': ['position', 'name_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[a-z0-9](?:[a-z0-9-]{0,30}[a-z0-9])?$', 'Use lowercase letters, numbers and hyphens, like wash-fold.', code='invalid_code')])),
                ('name_en', models.CharField(max_length=120)),
                ('name_sw', models.CharField(blank=True, max_length=120)),
                ('pricing_model', models.CharField(choices=[('per_kg', 'Per kg'), ('per_item', 'Per item'), ('flat', 'Flat')], max_length=8)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('item', 'item'), ('pair', 'pair'), ('set', 'set')], max_length=4)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
            ],
            options={
                'ordering': ['position', 'name_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceModifierService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.pricemodifier')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.service')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_sw', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['position', 'name_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.service')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='pricemodifier',
            constraint=models.UniqueConstraint(fields=('business', 'name_en'), name='modifier_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='pricemodifier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('percent__gt', 0), ('percent__isnull', False), ('amount__isnull', True)), models.Q(('amount__gt', 0), ('amount__isnull', False), ('percent__isnull', True)), _connector='OR'), name='modifier_percent_or_amount'),
        ),
        migrations.AddConstraint(
            model_name='pricemodifierservice',
            constraint=models.UniqueConstraint(fields=('business', 'modifier', 'service'), name='modifier_service_unique'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('business', 'name_en'), name='category_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='service_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pricing_model', 'per_kg'), ('unit', 'kg')), models.Q(models.Q(('pricing_model', 'per_kg'), _negated=True), models.Q(('unit', 'kg'), _negated=True)), _connector='OR'), name='service_unit_matches_pricing_model'),
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['business', 'service', 'effective_from'], name='price_service_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='price_unit_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_charge__gte', 0)), name='price_minimum_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='price_period_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('business', '='), ('service', '='), (django.db.models.functions.comparison.Coalesce('branch', models.Value('00000000-0000-0000-0000-000000000000', output_field=models.UUIDField())), '='), (apps.catalog.models.TsTzRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True)), '&&')], name='price_versions_never_overlap'),
        ),
        EnableTenantRLS("servicecategory"),
        EnableTenantRLS("service"),
        EnableTenantRLS("serviceprice"),
        EnableTenantRLS("pricemodifier"),
        EnableTenantRLS("pricemodifierservice"),
    ]
