# Generated by Django 5.2.17 on 2026-10-01 04:51

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

from apps.core.db import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_branding_and_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('rider', 'Rider'), ('customer', 'Customer'), ('platform_super_admin', 'Platform super admin'), ('platform_support', 'Platform support'), ('platform_finance', 'Platform finance')], max_length=24)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=2)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='active', max_length=12)),
                ('pin_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('pin_set_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('can_accept_cash', models.BooleanField(default=False)),
                ('can_give_discounts', models.BooleanField(default=False)),
                ('can_correct_prices', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
            ],
            options={
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('business__isnull', False)), fields=('business', 'phone'), name='user_unique_phone_per_business'), models.UniqueConstraint(condition=models.Q(('business__isnull', True)), fields=('phone',), name='platform_user_unique_phone'), models.CheckConstraint(condition=models.Q(('phone__regex', '^\\+254[17][0-9]{8}$')), name='user_phone_e164_ke_mobile'), models.CheckConstraint(condition=models.Q(models.Q(('business__isnull', True), ('role__in', ['platform_finance', 'platform_super_admin', 'platform_support'])), models.Q(models.Q(('role__in', ['platform_finance', 'platform_super_admin', 'platform_support']), _negated=True), ('business__isnull', False)), _connector='OR'), name='user_platform_roles_have_no_business')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        EnableTenantRLS("user"),
    ]
