# Generated by Django 5.2.17 on 2026-10-01 05:43

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.db import EnableTenantRLS


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenancy', '0002_branding_and_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('password', 'Password'), ('pin', 'PIN')], default='password', max_length=8)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=32)),
                ('refresh_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('previous_refresh_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'user', 'revoked_at'], name='session_user_active'), models.Index(fields=['previous_refresh_hash'], name='session_previous_refresh')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        EnableTenantRLS("usersession"),
    ]
