# Generated by Django 5.2.17 on 2026-10-01 06:13

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

from apps.core.db import EnableTenantRLS


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sessions'),
        ('tenancy', '0002_branding_and_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=16)),
                ('purpose', models.CharField(choices=[('password_reset', 'Password reset'), ('invitation', 'Invitation')], max_length=16)),
                ('code_hash', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('grant_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('grant_expires_at', models.DateTimeField(blank=True, null=True)),
                ('grant_used_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'phone', 'created_at'], name='otp_phone_time')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        EnableTenantRLS("phoneotp"),
    ]
