# Generated by Django 5.2.17 on 2026-10-01 06:39

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.db import EnableTenantRLS, MakeAppendOnly


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phone_codes'),
        ('branches', '0001_initial'),
        ('tenancy', '0002_branding_and_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('rider', 'Rider'), ('customer', 'Customer'), ('platform_super_admin', 'Platform super admin'), ('platform_support', 'Platform support'), ('platform_finance', 'Platform finance')], max_length=24)),
                ('can_accept_cash', models.BooleanField(default=False)),
                ('can_give_discounts', models.BooleanField(default=False)),
                ('can_correct_prices', models.BooleanField(default=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_count', models.PositiveSmallIntegerField(default=1)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InvitationBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.business')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.invitation')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('cancelled_at__isnull', True)), fields=('business', 'phone'), name='one_open_invitation_per_phone'),
        ),
        migrations.AddConstraint(
            model_name='invitationbranch',
            constraint=models.UniqueConstraint(fields=('business', 'invitation', 'branch'), name='invitation_branch_unique'),
        ),
        EnableTenantRLS("invitation"),
        EnableTenantRLS("invitationbranch"),
        EnableTenantRLS("consentrecord"),
        MakeAppendOnly("consentrecord"),
    ]
